[general]
import = [
    "$HOME/.config/alacritty/themes/themes/carbonfox.toml"
]

[window]
opacity = 0.85
blur = true

[cursor]
style = {shape = "Beam", blinking = "Off"}

[terminal]
shell = "/bin/zsh"

[font]
size = 16